:toc:
:toc-placement!:

:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

Here is my preamble paragraph, but I could really place the TOC anywhere! Lorem ipsum foo bar baz.

toc::[]

[NOTE]
====
A sample note admonition.
We can use gemoji icons in the Asciidoctor markup.
We assign an icon name to the document
attributes `tip-caption`, `note-caption` and `important-caption`.
====

TIP: It works!

IMPORTANT: Asciidoctor is awesome, don't forget!

CAUTION: Don't forget to add the `...-caption` document attributes in the header of the document on GitHub.

WARNING: You have no reason not to use Asciidoctor.

image::https://avatars3.githubusercontent.com/u/3137042?v=3&s=200[]

[source]
 ----
\ifdef::env-github[] <1> (1)
:imagesdir: https://gist.githubusercontent.com/path/to/gist/revision/dir/with/all/images
endif::[]
\ifndef::env-github[] <2>
:imagesdir: ./
endif::[]
 ----
<1> Use the `ifdef` to customize for online rendering (2)
<2> Use the `ifndef` to customize for offline

= Document Title
Ron Kurr <rkurr@jvmguy.com>
0.0.1.MILESTONE, 2012-01-01

== Level 1 Section

=== Level 2 Section

==== Level 3 Section

===== Level 4 Section

====== Level 5 Section

.Block Title
- Learn the AsciiDoc syntax
- Install AsciiDoc
- Write my document in AsciiDoc

# Context
. What is this software project/product/system all about?
. What is it that is being built?
. How does it fit into the existing environment? (e.g. systems, business processes, etc)
. Who is using it? (users, roles, actors, personas, etc)
. Context Diagram should be included
. Technical and non-technical audience
